name: 'Change Detection'
author: '@MassimilianoDH'
description: 'Check for changes in a directory'
inputs:
  make:
    description: 'Path to directory'
    required: true
  break:
    description: 'Path to directory'
    required: false
outputs:
  changes:
    description: 'List of changed files'
    value: ${{ steps.filter.outputs.changes }}
runs:
  using: 'composite'
  steps:
    - name: 'Apt Update'
      shell: bash
      run: sudo apt update && sudo apt install tree jq -y

    - name: 'List Make'
      shell: bash
      run: |
        bash list-dirs.sh ${{ inputs.make }}

    - name: 'List Break'
      shell: bash
      run: |
        bash list-dirs.sh ${{ inputs.break }}

    - name: 'Filter'
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: ./filters.yml