name: 'Change Detection'
author: '@MassimilianoDH'
description: 'Check for changes in a directory'
inputs:
  path:
    description: 'Path to directory'
    required: true
outputs:
  changes:
    description: 'List of changed files'
    value: ${{ steps.filter.outputs.changes }}
runs:
  using: 'composite'
  steps:
    - name: 'Apt Update'
      shell: bash
      run: sudo apt update && sudo apt install tree jq -y

    - name: 'List Directories'
      shell: bash
      id: list-dirs
      run: bash list-dirs.sh ${{ inputs.path }}

    - name: 'Filter'
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: ./filters.yml