name: 'Change Detection'
author: '@MassimilianoDH'
description: 'Check for changes in a directory'
inputs:
  path:
    description: 'Path to directory'
    required: true
  extension:
    description: 'File extension'
    required: true
outputs:
  changes:
    description: 'List of changed files'
    value: ${{ steps.filter.outputs.changes }}
runs:
  using: 'composite'
  steps:
    - name: 'List'
      shell: bash
      run: |
        bash ./.github/list-dirs.sh ${{ inputs.path }} ${{ inputs.extension }}

    - name: 'Filter'
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: ./filters.yml